name: Hello World

on:
  push:
    branches: [ main ]

jobs:
  hello:
    stage: hello-world
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World
        run: echo "Hello, world!"
  logs:
    stage: logs
    runs-on: ubuntu-latest
    steps:
      - name: Print Logs
        run: echo "Printing logs..."
