name: Hello World

on:
  push:
    branches: [main]

jobs:

  stages:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, world!"

  hello:
    needs: stages
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World
        run: echo "Hello, world!"

  commit_info:
    runs-on: ubuntu-latest
    steps:
      - name: Short commit
        run : |
          COMMIT_AUTHOR=$(git log -1 --format='%an <%ae>' $COMMIT_SHA)
          echo 'commit - ' $GITHUB_SHA ',' $COMMIT_AUTHOR 
