name: Hello World

on:
  push:
    branches: [ main ]

jobs:

  stages:
    - hello-world
    - logs

  hello:
    stage: hello-world
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World
        run: echo "Hello, world!"
