name: Hello World

on:
  push:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, world!"

  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Build index.ts
        run: npm install

      - name: Install dependencies
        run: npm run build

  commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Commit Information
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          echo "Commit SHA: $COMMIT_SHA"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Commit timestamp: ${{ github.event.head_commit.timestamp }}"

